- name: play1
  gather_facts: false
  hosts: web_servers

  vars:
    package_name: nginx
    package_version: latest

  tasks:

   - name: update
     apt: 
      update_cache: true
      name: "{{ package_name }}"
      state: "{{ package_version }}" 